import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import jobsIcon from "./assets/jobs.svg";
import roboto from "./lib/font-family";
import { ThemeProvider } from "@mui/material";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/react"


import theme from "./lib/theme";
import Container from "./components/container";

import contributorAlpha from "./assets/contributor-alpha.svg";
import contributorBeta from "./assets/contributor-beta.svg";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Remote Jobs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${roboto.className} ${roboto.variable} antialiased h-full flex flex-col`}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}></ThemeProvider>
          <header className="header  py-5">
            <Container>
              <Link href="/" className="flex items-center gap-5 w-fit">
                <Image src={jobsIcon} width={40} height={40} alt="Jobs Logo" />
                <h1 className="text-2xl">Remote Jobs</h1>
              </Link>

            </Container>
          </header>

          {children}

          <footer className="pb-5 mt-auto">
            <Container className="border-t border-gray-200 py-5">
              <p>This project was made possible by contributions from the open-source community.</p>
              <p className="lg:lex items-center gap-1">
                Contributors:{" "}
                <a className="inline-block align-middle" href="https://github.com/ghayasleo" target="_blank"><Image src={contributorAlpha} alt="Contributor" /></a>
                {" and "}
                <a className="inline-block align-middle" href="https://github.com/remoteintech" target="_blank"><Image src={contributorBeta} alt="Contributor" /></a>
                </p>
            </Container>
          </footer>
        </AppRouterCacheProvider>
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
